image:
  file: .devcontainer/Dockerfile
tasks:
  - init: npm install
vscode:
  extensions:
    - formulahendry.code-runner
    - github.vscode-pull-request-github
    - redhat.vscode-yaml
    - eamodio.gitlens
    - wix.vscode-import-cost
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - vscode-icons-team.vscode-icons
    - cschleiden.vscode-github-actions
    - oderwat.indent-rainbow
    - ms-azuretools.vscode-docker
