name: Publish dev npm package and Docker Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/*/**'
      - 'package-lock.json'
      - '.devcontainer/**'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: Edit Version
        run: |
          id_run1=$(echo ${{ github.run_id }} |cut -b 1-2)
          id_run2=$(echo ${{ github.run_id }} |cut -b 3-6)
          id_run3=$(echo ${{ github.run_id }} |cut -b 7-)
          old="$(cat package.json |grep "version"|head -1)"
          new_version="$id_run1.$id_run2.$id_run3"
          sed "s|$old|\"version\": \"$new_version\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdscore
          tags: bdsmaneger/core:nightly
          platforms: linux/amd64,linux/arm64,linux/arm/v7
