name: Publish dev npm package and Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKER_ARCH: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  CodeQL:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "javascript"

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        env:
          RunID: ${{ github.run_id }}
        run: node .github/ChangeVersion.js

      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_ORG_TOKEN }}'

  docker_core:
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@master

      - name: Bds Maneger Core Image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdscore
          tags: ghcr.io/the-bds-maneger/core:main
          platforms: ${{ env.DOCKER_ARCH }}

      - name: Bds Maneger base Image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdsbase
          tags: ghcr.io/the-bds-maneger/base:main
          platforms: ${{ env.DOCKER_ARCH }}
