name: Test - The Bds Maneger Core
on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Edit Version
      env:
          RunID: ${{ github.run_id }}
      run: node .github/ChangeVersion.js

    - name: Install node depedencies
      run: npm install -d --no-save
    
    - name: Run test
      run: npm run ci

  Test_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: checkout
        uses: actions/checkout@master

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          target: bdscore
          tags: coretest:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
