name: Publish
on:
  release:
    types:
      - prereleased
      - released

jobs:
  core:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    - name: Setup QEMU to Docker
      uses: docker/setup-qemu-action@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login into registry Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-node@v3.6.0
      name: Setup node.js
      with:
        registry-url: https://registry.npmjs.org/
        node-version: latest

    - name: Install dependecies
      run: npm install --no-save

    - name: Update version
      run: npm run updateversion -- ${{ github.event.release.tag_name }}

    - name: Publish
      run: npm --workspaces publish --access public --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build docker image
      uses: docker/build-push-action@v3
      with:
        cache-from: type=gha,scope=sirherobrine23_docker
        cache-to: type=gha,scope=sirherobrine23_docker
        platforms: "linux/amd64,linux/arm64"
        context: ./
        tags: ghcr.io/sirherobrine23/bdsmaneger
        push: true