name: Test Bds Core
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  buildTest:
    runs-on: ubuntu-latest
    name: Build Test (${{ matrix.node_version }})
    strategy:
      matrix:
        node_version:
          - "16"
          - "17"
          - "18"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup Node.js (Github Packages)
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "${{ matrix.node_version }}.x"

      - name: Install node depencies
        run: npm install -d

      - name: Build typescript
        run: npm run build

      - name: Test
        run: npm run test
