name: Docker And Node Test
on:
  pull_request:
    branches:
      - main

jobs:
  Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 15.x
          - 16.x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Edit Version
      env:
        RunID: ${{ github.run_id }}
      run: node .github/ChangeVersion.js

    - name: Install node depedencies
      run: npm install --no-save

    - name: Install node depedencies
      run: npm run esm_module
    
    - name: Run test
      run: npm test

  Docker-Build:
    needs: [Node]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: checkout
        uses: actions/checkout@master

      - name: Build Docker Image (Multiarch)
        id: DockerArch
        run: docker build --tag bdscore_pull:latest --file Dockerfile .

      # Run docker image with dev test
      - name: Run Docker Image (Multiarch)
        run: docker run --rm -i -e PULL_REQUEST="true" bdscore_pull:latest