name: Docker And Node Test
on:
  pull_request:
    branches:
      - main

jobs:
  CodeQL:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "javascript"

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 15.x
          - 16.x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Edit Version
      env:
        RunID: ${{ github.run_id }}
      run: node .github/ChangeVersion.js

    - name: Install node depedencies
      run: npm install --no-save
    
    - name: Run test
      run: npm test

  Docker-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm/v7

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: checkout
        uses: actions/checkout@master

      - name: Build Docker Image (Multiarch)
        id: DockerArch
        uses: docker/build-push-action@v2
        with:
          target: bdscore
          tags: coretestarch:latest
          platforms: linux/${{ matrix.arch }}
