name: Publish Releases
on:
  release:
    types:
      - created

env:
  DOCKER_ARCH: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  npm:
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == ${{ github.repository_owner }} && (contains('tag', ${{ github.ref }}) && contains('v', ${{ github.ref }}) || contains('V', ${{ github.ref }}))
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: npm install --no-save

      - name: Install node depedencies
        run: npm run esm_module
        
      - name: Publish
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_ORG_TOKEN }}'

      - name: Remove Dev Versions
        run: npm run cirelease
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_ORG_TOKEN }}'

  DockerImage:
    runs-on: ubuntu-latest
    name: Build Docker Image to Bds Core and Bds Base
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@master

      - name: Install Node Depedencies
        run: npm install --no-save -d

      - name: Get And Export Release Version
        run: node .Build/SetCIEnvs.js

      - name: Build Docker image (Bds Maneger Base)
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdsbase
          tags: |
            ghcr.io/the-bds-maneger/base:latest
            ghcr.io/the-bds-maneger/base:${{ env.BdsCoreVersion }}
          platforms: ${{ env.DOCKER_ARCH }}
      
      - name: Build Docker image (Bds Maneger core)
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdscore
          cache-from: ghcr.io/the-bds-maneger/base:latest
          tags: |
            ghcr.io/the-bds-maneger/core:latest
            ghcr.io/the-bds-maneger/core:${{ env.BdsCoreVersion }}
          platforms: ${{ env.DOCKER_ARCH }}
