name: "Publish Packages"
on:
  push:
    branches:
      - main
  release:
    types:
      - released
jobs:
  CodeQL:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "javascript"

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  test:
    strategy:
      matrix:
        node_version:
          - 16.x
          - 17.x
        os:
          - linux-latest
          - windows-latest
          - macos-latest
    name: "Test ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.JS and NPM
        uses: actions/setup-node@v2.5.1
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ matrix.node_version }}

      - name: Install Node Dependencies
        run: npm ci

      - name: Test
        run: npm test

  npm:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        npm_registry:
          - "Github"
          - "NPM"
    name: Npm Publish (${{ matrix.npm_registry }})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js (NPM Packages)
        if: matrix.npm_registry == 'NPM'
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Setup Node.js (Github Packages)
        if: matrix.npm_registry == 'Github'
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/


      - name: Edit Version to next release
        if: github.event_name != 'release'
        shell: node {0}
        run: |
          const fs = require("fs");
          const JsonPackage = JSON.parse(fs.readFileSync(process.cwd()+"/package.json", "utf8"));
          const run_ID = "${{ github.run_id }}";
          JsonPackage.version = `${run_ID.slice(0, 2)}.${run_ID.slice(3, 6)}.${run_ID.slice(7, 11)}`;
          fs.writeFileSync(process.cwd()+"/package.json", JSON.stringify(JsonPackage, null, 2));
          console.log("New Version to Package:", JsonPackage.version);

      - name: Install Node Dependencies
        run: npm install -d

      - name: ESM Modules
        run: npm run esm_module

      - name: Remove Dev Version
        if: github.event_name == 'release'
        shell: node {0}
        run: |
          const child_process = require("child_process");
          const fs = require("fs");
          const path = require("path");
          const cli_color = require("cli-color");
          (async function() {
            global.fetch = (await import("node-fetch")).default;
            fetch("https://registry.npmjs.org/@the-bds-maneger/core").then(res => res.json()).then(data => {
              data.versions = Object.getOwnPropertyNames(data.versions).filter(version => /[0-9]+\.[0-9][0-9][0-9]/.test(version) && version !== data["dist-tags"].dev && version !== data["dist-tags"].latest)
              fs.writeFileSync(path.resolve(__dirname, "Releases.json"), JSON.stringify(data, null, 2));
              const Package = require(process.cwd()+"/package.json");
              data.versions.map(version => {
                const cmd = `npm unpublish ${Package.name}@${version}`;
                console.log(cli_color.yellow(cmd));
                try {
                  child_process.execSync(cmd).toString()
                  console.log(cli_color.green(`Sucess to remove ${Package.name}@${version}`, "\n"));
                  return cmd;
                } catch (e) {
                  console.log(cli_color.red(`Failed to remove package: ${Package.name}@${version}`), "\n");
                  return version;
                }
              });
              fs.writeFileSync(path.resolve(__dirname, "Releases.json"), JSON.stringify(data, null, 2));
            });
          })();

      - name: Publish Package
        run: |
          set -x
          if [[ "${{ matrix.npm_registry }}" == "Github" ]];then
            echo "Publish to Github Packages"
            export NODE_AUTH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          else
            echo "Publish to NPM Registry"
            export NODE_AUTH_TOKEN="${{ secrets.NPM_ORG_TOKEN }}"
          fi
          if [[ "${{ github.event_name }}" == "release" ]];then
            npm publish
          else
            npm publish --tag next
          fi

  docker:
    runs-on: ubuntu-latest
    name: Publish Docker Image
    needs: [test]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.JS and NPM
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Edit Version to next release
        if: github.event_name != 'release'
        shell: node {0}
        run: |
          const fs = require("fs");
          const JsonPackage = JSON.parse(fs.readFileSync(process.cwd()+"/package.json", "utf8"));
          const run_ID = "${{ github.run_id }}";
          JsonPackage.version = `${run_ID.slice(0, 2)}.${run_ID.slice(3, 6)}.${run_ID.slice(7, 11)}`;
          fs.writeFileSync(process.cwd()+"/package.json", JSON.stringify(JsonPackage, null, 2));
          console.log("New Version to Package:", JsonPackage.version)

      - run: npm ci

      - name: Get Version and Set in Env
        shell: node {0}
        run: |
          const fs = require("fs");
          const { version } = require(process.cwd()+"/package.json");
          console.log(version);
          fs.appendFileSync(process.env.GITHUB_ENV, `CoreVersion=${version}`)

      - name: Build Bds Maneger Core (Release)
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/the-bds-maneger/core:latest
            ghcr.io/the-bds-maneger/core:${{ env.CoreVersion }}

      - name: Build Bds Maneger Core (Main)
        uses: docker/build-push-action@v2
        if: github.event_name != 'release'
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/the-bds-maneger/core:nightly
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/the-bds-maneger/core:nightly
