name: Spigot Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * 0"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/spigotBuild.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install 19 java
      uses: actions/setup-java@v3
      continue-on-error: true
      with:
        distribution: liberica
        java-version: "19"

    - name: Build
      continue-on-error: true
      run: |
        wget -qO build.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar build.jar --rev "latest"

    - name: Upload to actifial
      uses: actions/upload-artifact@v3
      with:
        name: latest
        path: "*.jar"

  # Upload
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install node depencies
      run: npm install --no-save

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Upload to actifial
      run: node .github/uploadToBucket.mjs SpigotBuild artifacts
      env:
        ociauth: "${{ secrets.OCI_AUTHKEY }}"
        OCI_AUTHKEY: "${{ secrets.OCI_AUTHKEY }}"