name: Spigot Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * 0"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/spigotBuild.yaml"
      - ".github/spigotBuilld/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - latest
        - "1.19.2"
        - "1.19.1"
        - "1.19"
        - "1.18.2"
        - "1.18.1"
        - "1.18-rc3"
        - "1.18-pre8"
        - "1.18-pre5"
        - "1.18"
        - "1.17.1"
        - "1.17"
        - "1.16.5"
        - "1.16.4"
        - "1.16.3"
        - "1.16.2"
        - "1.16.1"
        - "1.15.2"
        - "1.15.1"
        - "1.15"
        - "1.14.4"
        - "1.14.3-pre4"
        - "1.14.3"
        - "1.14.2"
        - "1.14.1"
        - "1.14-pre5"
        - "1.14"
        - "1.13.2"
        - "1.13.1"
        - "1.13-pre7"
        - "1.13"
        - "1.12.2"
        - "1.12.1"
        - "1.12"
        - "1.11.2"
        - "1.11.1"
        - "1.11"
        - "1.10.2"
        - "1.10"
        - "1.9.4"
        - "1.9.2"
        - "1.9"
        - "1.8.8"
        - "1.8.7"
        - "1.8.6"
        - "1.8.5"
        - "1.8.4"
        - "1.8.3"
        - "1.8"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    - name: Install ${{ startsWith(matrix.version, 'latest') && '19' || (startsWith(matrix.version, '1.19')||startsWith(matrix.version, '1.18')) && '17' || startsWith(matrix.version, '1.17') && '16' || '8' }} java
      uses: actions/setup-java@v3
      continue-on-error: true
      with:
        distribution: liberica
        java-version: ${{ (startsWith(matrix.version, 'latest')||startsWith(matrix.version, '1.19')||startsWith(matrix.version, '1.18')) && '17' || startsWith(matrix.version, '1.17') && '16' || '8' }}


    - uses: actions/setup-node@v3
      name: Setup node.js
      with:
        node-version: 18.x

    - run: npm install --no-save && node .github/spigotBuilld/index.mjs --version=${{ matrix.version || 'latest' }}
      continue-on-error: true
      env:
        OCI_AUTHKEY: "${{ secrets.OCI_AUTHKEY }}"