name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - "@the-bds-maneger/core"
          - "@the-bds-maneger/web"
          - "bds-maneger"
          - "@the-bds-maneger/verapi"
    name: "Testing \"${{ matrix.package }}\""
    env:
      bdscoreroot: "~/.bdsCore"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    # Install basic tools
    - uses: actions/setup-node@v3.6.0
      name: Setup node.js
      with:
        node-version: latest

    - name: Install latest java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "17"

    # Install dependecies
    - name: Install nodejs dependencies
      run: npm install --no-save

    # Build Core
    - name: Core Build
      if: matrix.package != '@the-bds-maneger/core'
      run: npm run -w "@the-bds-maneger/core" build

    - name: Build "${{ matrix.package }}"
      run: npm run --if-present -w "${{ matrix.package }}" prepack