name: Test Bds Core
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test (Node version: ${{ matrix.node_version }})"
    strategy:
      matrix:
        node_version:
          - "18"
          - "17"
          - "16"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Node.js (Github Packages)
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "${{ matrix.node_version }}.x"

      - name: Install latest java
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Install node depencies
        run: npm ci

      - name: Test
        run: npm run test -- --exit-on-error --show-return
