name: Test platforms
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test_prebuild:
    strategy:
      matrix:
        platform:
        - Bedrock
        - Powernukkit
        - Java
        - Paper
        - Pocketmine
        - Spigot
    runs-on: ubuntu-latest
    name: "${{ matrix.platform }}"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    # Install basic tools
    - uses: actions/setup-node@v3
      name: Setup node.js
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/

    - name: Install latest java
      uses: actions/setup-java@v3
      if: matrix.platform == 'Java' || matrix.platform == 'Paper' || matrix.platform == 'Spigot' || matrix.platform == 'Powernukkit'
      with:
        distribution: temurin
        java-version: "17"

    - name: Install apt dependecies to Pocketmine
      if: matrix.platform == 'Pocketmine'
      run: |
        sudo apt update
        sudo apt install -y build-essential make wget gzip bzip2 bison git cmake re2c autoconf automake pkg-config libtool* unzip zip tar

    # Install dependecies
    - name: Install nodejs dependencies
      run: npm ci

    # Run test
    - name: Test
      run: npm run test:partial -- tests/${{ matrix.platform }}.ts